{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "title": { "type": "text" },
      "kind": { "type": "text" },
      "author": { "type": "text" },
      "description": { "type": "text" }
    }
  }
}
